import type { SloganCategory } from '@/lib/slogans';

export interface ClassroomCategory extends SloganCategory {
  description: string;
}

/**
 * Ngân hàng câu lệnh lớp học (Classroom English) cho giáo viên tiếng Anh tiểu học.
 * Phiên âm IPA theo giọng General American.
 */
export const classroomCategories: ClassroomCategory[] = [
  {
    id: 'cl-greetings',
    name: 'Chào hỏi & mở đầu',
    icon: '👋',
    description: 'Chào lớp, điểm danh, hỏi thăm và bắt đầu bài học',
    slogans: [
      { en: 'Good morning, class!', ipa: '/ɡʊd ˈmɔːrnɪŋ, klæs/', vi: 'Chào buổi sáng cả lớp!' },
      { en: 'Good afternoon, everyone!', ipa: '/ɡʊd ˌæftərˈnuːn, ˈɛvriwʌn/', vi: 'Chào buổi chiều cả lớp!' },
      { en: 'How are you today?', ipa: '/haʊ ɑːr juː təˈdeɪ/', vi: 'Hôm nay các em thế nào?' },
      { en: "I'm fine, thank you. And you?", ipa: '/aɪm faɪn, θæŋk juː. ænd juː/', vi: 'Em khỏe, cảm ơn thầy/cô. Còn thầy/cô ạ?' },
      { en: 'Nice to see you again!', ipa: '/naɪs tə siː juː əˈɡɛn/', vi: 'Rất vui được gặp lại các em!' },
      { en: 'Who is absent today?', ipa: '/huː ɪz ˈæbsənt təˈdeɪ/', vi: 'Hôm nay ai vắng mặt?' },
      { en: 'What day is it today?', ipa: '/wʌt deɪ ɪz ɪt təˈdeɪ/', vi: 'Hôm nay là thứ mấy?' },
      { en: "What's the weather like today?", ipa: '/wʌts ðə ˈwɛðər laɪk təˈdeɪ/', vi: 'Thời tiết hôm nay thế nào?' },
      { en: 'Are you ready to learn?', ipa: '/ɑːr juː ˈrɛdi tə lɜːrn/', vi: 'Các em đã sẵn sàng học chưa?' },
      { en: "Let's start our lesson.", ipa: '/lɛts stɑːrt ˈaʊər ˈlɛsən/', vi: 'Chúng ta bắt đầu bài học nhé.' },
      { en: "Let's review the last lesson.", ipa: '/lɛts rɪˈvjuː ðə læst ˈlɛsən/', vi: 'Cùng ôn lại bài trước nào.' },
      { en: "Today we're going to learn about animals.", ipa: '/təˈdeɪ wɪr ˈɡoʊɪŋ tə lɜːrn əˈbaʊt ˈænəməlz/', vi: 'Hôm nay chúng ta sẽ học về các con vật.' },
      { en: "Let's sing a song together.", ipa: '/lɛts sɪŋ ə sɔːŋ təˈɡɛðər/', vi: 'Cùng hát một bài nhé.' },
      { en: 'Welcome back to class!', ipa: '/ˈwɛlkəm bæk tə klæs/', vi: 'Chào mừng các em trở lại lớp!' },
      { en: 'Happy Monday, everyone!', ipa: '/ˈhæpi ˈmʌndeɪ, ˈɛvriwʌn/', vi: 'Chúc cả lớp ngày thứ Hai vui vẻ!' },
    ],
  },
  {
    id: 'cl-instructions',
    name: 'Hướng dẫn hoạt động',
    icon: '📋',
    description: 'Mở sách, nghe – nhắc lại, làm việc cặp/nhóm, làm bài tập',
    slogans: [
      { en: 'Open your books to page ten.', ipa: '/ˈoʊpən jʊr bʊks tə peɪdʒ tɛn/', vi: 'Các em mở sách trang 10.' },
      { en: 'Close your books, please.', ipa: '/kloʊz jʊr bʊks, pliːz/', vi: 'Các em gấp sách lại nhé.' },
      { en: 'Look at the board.', ipa: '/lʊk æt ðə bɔːrd/', vi: 'Các em nhìn lên bảng.' },
      { en: 'Listen and repeat.', ipa: '/ˈlɪsən ænd rɪˈpiːt/', vi: 'Nghe và nhắc lại.' },
      { en: 'Listen carefully.', ipa: '/ˈlɪsən ˈkɛrfəli/', vi: 'Các em lắng nghe cẩn thận nhé.' },
      { en: 'Read after me.', ipa: '/riːd ˈæftər miː/', vi: 'Đọc theo thầy/cô.' },
      { en: 'Work in pairs.', ipa: '/wɜːrk ɪn pɛrz/', vi: 'Làm việc theo cặp.' },
      { en: 'Work in groups of four.', ipa: '/wɜːrk ɪn ɡruːps əv fɔːr/', vi: 'Làm việc theo nhóm bốn bạn.' },
      { en: 'Take out your pencils.', ipa: '/teɪk aʊt jʊr ˈpɛnsəlz/', vi: 'Các em lấy bút chì ra.' },
      { en: 'Write your name here.', ipa: '/raɪt jʊr neɪm hɪr/', vi: 'Viết tên của em vào đây.' },
      { en: 'Point to the picture.', ipa: '/pɔɪnt tə ðə ˈpɪktʃər/', vi: 'Chỉ vào bức tranh.' },
      { en: 'Match the words with the pictures.', ipa: '/mætʃ ðə wɜːrdz wɪð ðə ˈpɪktʃərz/', vi: 'Nối từ với tranh.' },
      { en: 'Circle the correct answer.', ipa: '/ˈsɜːrkəl ðə kəˈrɛkt ˈænsər/', vi: 'Khoanh tròn đáp án đúng.' },
      { en: 'Raise your hand, please.', ipa: '/reɪz jʊr hænd, pliːz/', vi: 'Các em giơ tay nhé.' },
      { en: 'You have five minutes.', ipa: '/juː hæv faɪv ˈmɪnɪts/', vi: 'Các em có năm phút.' },
      { en: "Let's check the answers together.", ipa: '/lɛts tʃɛk ði ˈænsərz təˈɡɛðər/', vi: 'Cùng kiểm tra đáp án nào.' },
    ],
  },
  {
    id: 'cl-praise',
    name: 'Khen ngợi & động viên',
    icon: '🌟',
    description: 'Lời khen, động viên khi học sinh làm tốt hoặc chưa đúng',
    slogans: [
      { en: 'Good job!', ipa: '/ɡʊd dʒɑːb/', vi: 'Làm tốt lắm!' },
      { en: 'Well done!', ipa: '/wɛl dʌn/', vi: 'Giỏi lắm!' },
      { en: 'Excellent!', ipa: '/ˈɛksələnt/', vi: 'Xuất sắc!' },
      { en: 'Great work, everyone!', ipa: '/ɡreɪt wɜːrk, ˈɛvriwʌn/', vi: 'Cả lớp làm rất tốt!' },
      { en: "That's right!", ipa: '/ðæts raɪt/', vi: 'Đúng rồi!' },
      { en: 'Very good!', ipa: '/ˈvɛri ɡʊd/', vi: 'Rất tốt!' },
      { en: 'Nice try!', ipa: '/naɪs traɪ/', vi: 'Em đã cố gắng tốt lắm!' },
      { en: 'Almost! Try again.', ipa: '/ˈɔːlmoʊst. traɪ əˈɡɛn/', vi: 'Gần đúng rồi! Thử lại nhé.' },
      { en: "Don't worry, you can do it.", ipa: '/doʊnt ˈwɜːri, juː kæn duː ɪt/', vi: 'Đừng lo, em làm được mà.' },
      { en: "I'm proud of you!", ipa: '/aɪm praʊd əv juː/', vi: 'Thầy/cô tự hào về em!' },
      { en: "You're a star!", ipa: '/jʊr ə stɑːr/', vi: 'Em là ngôi sao!' },
      { en: 'Give him a big hand!', ipa: '/ɡɪv hɪm ə bɪɡ hænd/', vi: 'Cho bạn một tràng pháo tay nào!' },
      { en: 'What a beautiful picture!', ipa: '/wʌt ə ˈbjuːtəfəl ˈpɪktʃər/', vi: 'Bức tranh đẹp quá!' },
      { en: 'Your handwriting is very neat.', ipa: '/jʊr ˈhændˌraɪtɪŋ ɪz ˈvɛri niːt/', vi: 'Chữ viết của em rất gọn gàng.' },
      { en: 'Keep up the good work!', ipa: '/kiːp ʌp ðə ɡʊd wɜːrk/', vi: 'Tiếp tục phát huy nhé!' },
      { en: "You're getting better and better!", ipa: '/jʊr ˈɡɛtɪŋ ˈbɛtər ænd ˈbɛtər/', vi: 'Em ngày càng tiến bộ!' },
    ],
  },
  {
    id: 'cl-management',
    name: 'Quản lý lớp học',
    icon: '🤫',
    description: 'Ổn định trật tự, di chuyển, giữ gìn lớp học',
    slogans: [
      { en: 'Stand up, please.', ipa: '/stænd ʌp, pliːz/', vi: 'Các em đứng lên nào.' },
      { en: 'Sit down, please.', ipa: '/sɪt daʊn, pliːz/', vi: 'Mời các em ngồi xuống.' },
      { en: 'Be quiet, please.', ipa: '/biː ˈkwaɪət, pliːz/', vi: 'Các em trật tự nào.' },
      { en: 'Eyes on me, please.', ipa: '/aɪz ɑːn miː, pliːz/', vi: 'Các em nhìn thầy/cô nhé.' },
      { en: 'One, two, three — eyes on me!', ipa: '/wʌn, tuː, θriː — aɪz ɑːn miː/', vi: 'Một, hai, ba — nhìn thầy/cô!' },
      { en: 'Line up, please.', ipa: '/laɪn ʌp, pliːz/', vi: 'Các em xếp hàng nhé.' },
      { en: 'Come here, please.', ipa: '/kʌm hɪr, pliːz/', vi: 'Em lên đây nào.' },
      { en: 'Go back to your seat.', ipa: '/ɡoʊ bæk tə jʊr siːt/', vi: 'Em về chỗ ngồi nhé.' },
      { en: "Don't talk, please.", ipa: '/doʊnt tɔːk, pliːz/', vi: 'Các em đừng nói chuyện nhé.' },
      { en: 'Please speak louder.', ipa: '/pliːz spiːk ˈlaʊdər/', vi: 'Em nói to hơn nhé.' },
      { en: 'Hands up if you know the answer.', ipa: '/hændz ʌp ɪf juː noʊ ði ˈænsər/', vi: 'Ai biết đáp án thì giơ tay.' },
      { en: 'Put your hands down.', ipa: '/pʊt jʊr hændz daʊn/', vi: 'Các em bỏ tay xuống.' },
      { en: 'Take turns, please.', ipa: '/teɪk tɜːrnz, pliːz/', vi: 'Các em lần lượt nhé.' },
      { en: 'Please clean up your desk.', ipa: '/pliːz kliːn ʌp jʊr dɛsk/', vi: 'Các em dọn bàn học nhé.' },
      { en: "Walk, don't run.", ipa: '/wɔːk, doʊnt rʌn/', vi: 'Đi bộ, không chạy nhé.' },
    ],
  },
  {
    id: 'cl-games',
    name: 'Trò chơi',
    icon: '🎲',
    description: 'Chia đội, đến lượt, tính điểm, công bố đội thắng',
    slogans: [
      { en: "Let's play a game!", ipa: '/lɛts pleɪ ə ɡeɪm/', vi: 'Cùng chơi một trò chơi nào!' },
      { en: 'Make two teams.', ipa: '/meɪk tuː tiːmz/', vi: 'Chia thành hai đội.' },
      { en: 'This is Team A, and this is Team B.', ipa: '/ðɪs ɪz tiːm eɪ, ænd ðɪs ɪz tiːm biː/', vi: 'Đây là đội A, còn đây là đội B.' },
      { en: "It's your turn.", ipa: '/ɪts jʊr tɜːrn/', vi: 'Đến lượt em.' },
      { en: 'Whose turn is it?', ipa: '/huːz tɜːrn ɪz ɪt/', vi: 'Đến lượt ai?' },
      { en: 'Roll the dice.', ipa: '/roʊl ðə daɪs/', vi: 'Gieo xúc xắc nào.' },
      { en: 'Pick a card.', ipa: '/pɪk ə kɑːrd/', vi: 'Chọn một lá thẻ.' },
      { en: 'Ready, steady, go!', ipa: '/ˈrɛdi, ˈstɛdi, ɡoʊ/', vi: 'Chuẩn bị, sẵn sàng, bắt đầu!' },
      { en: "Time's up!", ipa: '/taɪmz ʌp/', vi: 'Hết giờ!' },
      { en: 'One point for Team A!', ipa: '/wʌn pɔɪnt fər tiːm eɪ/', vi: 'Đội A được một điểm!' },
      { en: 'Who wants to try?', ipa: '/huː wɑːnts tə traɪ/', vi: 'Ai muốn thử nào?' },
      { en: 'Guess what it is.', ipa: '/ɡɛs wʌt ɪt ɪz/', vi: 'Đoán xem đó là gì.' },
      { en: 'Simon says, touch your nose.', ipa: '/ˈsaɪmən sɛz, tʌtʃ jʊr noʊz/', vi: 'Simon bảo: chạm vào mũi.' },
      { en: "Let's count the points.", ipa: '/lɛts kaʊnt ðə pɔɪnts/', vi: 'Cùng đếm điểm nào.' },
      { en: 'The winner is Team B!', ipa: '/ðə ˈwɪnər ɪz tiːm biː/', vi: 'Đội thắng là đội B!' },
      { en: 'Play fair, please.', ipa: '/pleɪ fɛr, pliːz/', vi: 'Chơi công bằng nhé.' },
    ],
  },
  {
    id: 'cl-closing',
    name: 'Kết thúc tiết học',
    icon: '🔔',
    description: 'Tóm tắt bài, giao bài về nhà, chào tạm biệt',
    slogans: [
      { en: 'Time to stop.', ipa: '/taɪm tə stɑːp/', vi: 'Đến giờ dừng lại rồi.' },
      { en: "That's all for today.", ipa: '/ðæts ɔːl fər təˈdeɪ/', vi: 'Bài học hôm nay đến đây là hết.' },
      { en: 'What did we learn today?', ipa: '/wʌt dɪd wiː lɜːrn təˈdeɪ/', vi: 'Hôm nay chúng ta đã học gì?' },
      { en: "Let's sum up the lesson.", ipa: '/lɛts sʌm ʌp ðə ˈlɛsən/', vi: 'Cùng tóm tắt bài học nhé.' },
      { en: 'Your homework is on page twelve.', ipa: '/jʊr ˈhoʊmwɜːrk ɪz ɑːn peɪdʒ twɛlv/', vi: 'Bài tập về nhà ở trang 12.' },
      { en: 'Practice at home, please.', ipa: '/ˈpræktɪs æt hoʊm, pliːz/', vi: 'Các em luyện tập ở nhà nhé.' },
      { en: "Don't forget your homework.", ipa: '/doʊnt fərˈɡɛt jʊr ˈhoʊmwɜːrk/', vi: 'Đừng quên bài tập về nhà nhé.' },
      { en: 'Put your things away.', ipa: '/pʊt jʊr θɪŋz əˈweɪ/', vi: 'Các em cất đồ dùng đi.' },
      { en: 'Thank you for listening.', ipa: '/θæŋk juː fər ˈlɪsənɪŋ/', vi: 'Cảm ơn các em đã lắng nghe.' },
      { en: 'You did a great job today.', ipa: '/juː dɪd ə ɡreɪt dʒɑːb təˈdeɪ/', vi: 'Hôm nay các em làm rất tốt.' },
      { en: 'See you next time!', ipa: '/siː juː nɛkst taɪm/', vi: 'Hẹn gặp lại các em lần sau!' },
      { en: 'See you tomorrow!', ipa: '/siː juː təˈmɑːroʊ/', vi: 'Hẹn gặp lại ngày mai!' },
      { en: 'Goodbye, class!', ipa: '/ɡʊdˈbaɪ, klæs/', vi: 'Tạm biệt cả lớp!' },
      { en: 'Have a nice weekend!', ipa: '/hæv ə naɪs ˈwiːkɛnd/', vi: 'Chúc các em cuối tuần vui vẻ!' },
      { en: 'Goodbye, teacher!', ipa: '/ɡʊdˈbaɪ, ˈtiːtʃər/', vi: 'Chúng em chào thầy/cô ạ!' },
    ],
  },
  {
    id: 'cl-student-teacher',
    name: 'Học sinh nói với thầy cô',
    icon: '🙋',
    description: 'Xin phép, đặt câu hỏi, nhờ giúp đỡ lịch sự',
    slogans: [
      { en: 'May I come in?', ipa: '/meɪ aɪ kʌm ɪn/', vi: 'Em vào lớp được không ạ?' },
      { en: 'May I go out?', ipa: '/meɪ aɪ ɡoʊ aʊt/', vi: 'Em ra ngoài được không ạ?' },
      { en: 'May I go to the toilet, please?', ipa: '/meɪ aɪ ɡoʊ tə ðə ˈtɔɪlət, pliːz/', vi: 'Em đi vệ sinh được không ạ?' },
      { en: 'May I ask a question?', ipa: '/meɪ aɪ æsk ə ˈkwɛstʃən/', vi: 'Em hỏi một câu được không ạ?' },
      { en: 'Can you help me, please?', ipa: '/kæn juː hɛlp miː, pliːz/', vi: 'Thầy/cô giúp em với ạ.' },
      { en: 'Can you say that again, please?', ipa: '/kæn juː seɪ ðæt əˈɡɛn, pliːz/', vi: 'Thầy/cô nói lại được không ạ?' },
      { en: "Sorry, I don't understand.", ipa: '/ˈsɑːri, aɪ doʊnt ˌʌndərˈstænd/', vi: 'Em xin lỗi, em chưa hiểu ạ.' },
      { en: 'How do you say this in English?', ipa: '/haʊ duː juː seɪ ðɪs ɪn ˈɪŋɡlɪʃ/', vi: 'Cái này nói bằng tiếng Anh thế nào ạ?' },
      { en: 'What does this word mean?', ipa: '/wʌt dʌz ðɪs wɜːrd miːn/', vi: 'Từ này nghĩa là gì ạ?' },
      { en: 'How do you spell it?', ipa: '/haʊ duː juː spɛl ɪt/', vi: 'Từ đó đánh vần thế nào ạ?' },
      { en: "I'm sorry I'm late.", ipa: '/aɪm ˈsɑːri aɪm leɪt/', vi: 'Em xin lỗi vì đến muộn ạ.' },
      { en: 'I have finished.', ipa: '/aɪ hæv ˈfɪnɪʃt/', vi: 'Em làm xong rồi ạ.' },
      { en: 'I forgot my book.', ipa: '/aɪ fərˈɡɑːt maɪ bʊk/', vi: 'Em quên sách ạ.' },
      { en: 'Can I borrow a pencil?', ipa: '/kæn aɪ ˈbɑːroʊ ə ˈpɛnsəl/', vi: 'Em mượn một cái bút chì được không ạ?' },
      { en: 'Thank you, teacher.', ipa: '/θæŋk juː, ˈtiːtʃər/', vi: 'Em cảm ơn thầy/cô ạ.' },
    ],
  },
  {
    id: 'cl-student-student',
    name: 'Học sinh với học sinh',
    icon: '🤝',
    description: 'Làm quen, hợp tác, cảm ơn – xin lỗi giữa các bạn',
    slogans: [
      { en: "Hello! What's your name?", ipa: '/həˈloʊ! wʌts jʊr neɪm/', vi: 'Xin chào! Bạn tên là gì?' },
      { en: 'My name is Nam.', ipa: '/maɪ neɪm ɪz nɑːm/', vi: 'Mình tên là Nam.' },
      { en: 'Nice to meet you.', ipa: '/naɪs tə miːt juː/', vi: 'Rất vui được gặp bạn.' },
      { en: 'How old are you?', ipa: '/haʊ oʊld ɑːr juː/', vi: 'Bạn bao nhiêu tuổi?' },
      { en: 'Can I sit here?', ipa: '/kæn aɪ sɪt hɪr/', vi: 'Mình ngồi đây được không?' },
      { en: 'Sure, sit next to me.', ipa: '/ʃʊr, sɪt nɛkst tə miː/', vi: 'Được chứ, ngồi cạnh mình nhé.' },
      { en: "Let's work together.", ipa: '/lɛts wɜːrk təˈɡɛðər/', vi: 'Chúng mình cùng làm nhé.' },
      { en: "It's your turn now.", ipa: '/ɪts jʊr tɜːrn naʊ/', vi: 'Bây giờ đến lượt bạn.' },
      { en: 'Can you help me?', ipa: '/kæn juː hɛlp miː/', vi: 'Bạn giúp mình được không?' },
      { en: 'Here you are.', ipa: '/hɪr juː ɑːr/', vi: 'Của bạn đây.' },
      { en: 'Thank you so much!', ipa: '/θæŋk juː soʊ mʌtʃ/', vi: 'Cảm ơn bạn nhiều!' },
      { en: "You're welcome.", ipa: '/jʊr ˈwɛlkəm/', vi: 'Không có gì.' },
      { en: "I'm sorry.", ipa: '/aɪm ˈsɑːri/', vi: 'Mình xin lỗi.' },
      { en: "That's OK.", ipa: '/ðæts oʊˈkeɪ/', vi: 'Không sao đâu.' },
      { en: "Let's play together at break time.", ipa: '/lɛts pleɪ təˈɡɛðər æt breɪk taɪm/', vi: 'Giờ ra chơi mình cùng chơi nhé.' },
      { en: 'See you later!', ipa: '/siː juː ˈleɪtər/', vi: 'Hẹn gặp lại bạn sau!' },
    ],
  },
];

export const CLASSROOM_PHRASE_COUNT = classroomCategories.reduce((sum, c) => sum + c.slogans.length, 0);
